// <auto-generated />
using System;
using CMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230320085715_update_seed")]
    partial class update_seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Model.BasicField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Required")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.ToTable("Fields");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2b927bb-08a3-46d9-9a44-1100a839a819"),
                            ContentTypeId = new Guid("2aca0bee-c175-4d0f-8495-44d8be5eef25"),
                            Name = "Creator",
                            Type = 0,
                            Value = "Regixx"
                        },
                        new
                        {
                            Id = new Guid("c435f36d-3e16-49c8-b98a-7be4337f5dad"),
                            ContentTypeId = new Guid("2aca0bee-c175-4d0f-8495-44d8be5eef25"),
                            Name = "TrailerVideo",
                            Type = 4,
                            Value = "http://"
                        },
                        new
                        {
                            Id = new Guid("3cfc3654-925d-4b9c-b7a5-320e85b2cdac"),
                            ContentTypeId = new Guid("0f0197f4-a460-4315-afbb-86180872a89b"),
                            Name = "DescriptionText",
                            Type = 0,
                            Value = "Best game ever"
                        },
                        new
                        {
                            Id = new Guid("42ad829a-1f18-4e7f-b855-6a1d722af24d"),
                            ContentTypeId = new Guid("2c33469c-f3f1-49c7-8808-1148eebcf984"),
                            Name = "Name",
                            Type = 0,
                            Value = "Star Wars"
                        },
                        new
                        {
                            Id = new Guid("f1973d16-0ea1-4497-b517-7c3abe4aebb5"),
                            ContentTypeId = new Guid("2c33469c-f3f1-49c7-8808-1148eebcf984"),
                            Name = "Year",
                            Type = 1,
                            Value = "2007"
                        },
                        new
                        {
                            Id = new Guid("0e04bb7e-ae73-42ea-846d-4009fcaec7bb"),
                            ContentTypeId = new Guid("060111b3-0c12-4559-ba21-cf8b3eb9e170"),
                            Name = "Name",
                            Type = 0,
                            Value = "Santa Monica"
                        },
                        new
                        {
                            Id = new Guid("98b5bf32-0b90-4d40-861d-f94f03c7caa5"),
                            ContentTypeId = new Guid("060111b3-0c12-4559-ba21-cf8b3eb9e170"),
                            Name = "Location",
                            Type = 0,
                            Value = "USA"
                        });
                });

            modelBuilder.Entity("CMS.Model.ContentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("SpaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SysId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SysId");

                    b.ToTable("ContentTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2aca0bee-c175-4d0f-8495-44d8be5eef25"),
                            Name = "Trailer",
                            SpaceId = new Guid("6c2521da-4e11-4dec-b01c-8d4d89e47eb9")
                        },
                        new
                        {
                            Id = new Guid("0f0197f4-a460-4315-afbb-86180872a89b"),
                            Name = "Description",
                            SpaceId = new Guid("6c2521da-4e11-4dec-b01c-8d4d89e47eb9")
                        },
                        new
                        {
                            Id = new Guid("2c33469c-f3f1-49c7-8808-1148eebcf984"),
                            Name = "Game",
                            SpaceId = new Guid("6c2521da-4e11-4dec-b01c-8d4d89e47eb9")
                        },
                        new
                        {
                            Id = new Guid("060111b3-0c12-4559-ba21-cf8b3eb9e170"),
                            Name = "Publisher",
                            SpaceId = new Guid("6c2521da-4e11-4dec-b01c-8d4d89e47eb9")
                        });
                });

            modelBuilder.Entity("CMS.Model.ContentTypeReferences", b =>
                {
                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("ContentTypeReferences");

                    b.HasData(
                        new
                        {
                            ParentId = new Guid("0f0197f4-a460-4315-afbb-86180872a89b"),
                            ChildId = new Guid("2aca0bee-c175-4d0f-8495-44d8be5eef25")
                        },
                        new
                        {
                            ParentId = new Guid("2c33469c-f3f1-49c7-8808-1148eebcf984"),
                            ChildId = new Guid("0f0197f4-a460-4315-afbb-86180872a89b")
                        },
                        new
                        {
                            ParentId = new Guid("2c33469c-f3f1-49c7-8808-1148eebcf984"),
                            ChildId = new Guid("060111b3-0c12-4559-ba21-cf8b3eb9e170")
                        });
                });

            modelBuilder.Entity("CMS.Model.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("229c238d-2fbd-47ae-a5b6-6be61cb8a9b2"),
                            Name = "Org1"
                        },
                        new
                        {
                            Id = new Guid("3b795dea-e3da-428a-aa59-3850a4382b18"),
                            Name = "Organization 2"
                        },
                        new
                        {
                            Id = new Guid("32cc0321-3bba-4f7b-b1ce-5d5e146185c9"),
                            Name = "Third oorg"
                        });
                });

            modelBuilder.Entity("CMS.Model.Space", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Spaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c2521da-4e11-4dec-b01c-8d4d89e47eb9"),
                            Name = "Game shop",
                            OrganizationId = new Guid("229c238d-2fbd-47ae-a5b6-6be61cb8a9b2")
                        });
                });

            modelBuilder.Entity("CMS.Model.Sys", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FirstPublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sys");
                });

            modelBuilder.Entity("CMS.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b186191f-0c90-463a-86e5-76a308e139e5"),
                            UserRole = 0
                        },
                        new
                        {
                            Id = new Guid("1b8b6c51-82ba-460a-8945-69d64c193827"),
                            UserRole = 1
                        },
                        new
                        {
                            Id = new Guid("35045e7d-6c48-41e6-abfe-5db698ad1151"),
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("Models.OrganizationUser", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrganizationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OrganizationUser");

                    b.HasData(
                        new
                        {
                            OrganizationId = new Guid("229c238d-2fbd-47ae-a5b6-6be61cb8a9b2"),
                            UserId = new Guid("b186191f-0c90-463a-86e5-76a308e139e5")
                        },
                        new
                        {
                            OrganizationId = new Guid("229c238d-2fbd-47ae-a5b6-6be61cb8a9b2"),
                            UserId = new Guid("1b8b6c51-82ba-460a-8945-69d64c193827")
                        });
                });

            modelBuilder.Entity("CMS.Model.BasicField", b =>
                {
                    b.HasOne("CMS.Model.ContentType", "ContentType")
                        .WithMany("BasicFields")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");
                });

            modelBuilder.Entity("CMS.Model.ContentType", b =>
                {
                    b.HasOne("CMS.Model.Sys", "Sys")
                        .WithMany()
                        .HasForeignKey("SysId");

                    b.Navigation("Sys");
                });

            modelBuilder.Entity("CMS.Model.ContentTypeReferences", b =>
                {
                    b.HasOne("CMS.Model.ContentType", "ChildEntity")
                        .WithMany("Parents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CMS.Model.ContentType", "ParentEntity")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildEntity");

                    b.Navigation("ParentEntity");
                });

            modelBuilder.Entity("CMS.Model.Space", b =>
                {
                    b.HasOne("CMS.Model.Organization", "Organization")
                        .WithMany("Spaces")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Models.OrganizationUser", b =>
                {
                    b.HasOne("CMS.Model.Organization", "Organization")
                        .WithMany("OrganizationUser")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CMS.Model.User", "User")
                        .WithMany("OrganizationUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CMS.Model.ContentType", b =>
                {
                    b.Navigation("BasicFields");

                    b.Navigation("Children");

                    b.Navigation("Parents");
                });

            modelBuilder.Entity("CMS.Model.Organization", b =>
                {
                    b.Navigation("OrganizationUser");

                    b.Navigation("Spaces");
                });

            modelBuilder.Entity("CMS.Model.User", b =>
                {
                    b.Navigation("OrganizationUser");
                });
#pragma warning restore 612, 618
        }
    }
}
